k: 6

fcgr_from_msa:
  folder_msa: 'data/msas'
  path_fcgr: 'data/fcgr'

train:
  latent_dim: 100
  epochs: 20  
  batch_size: 16
  architecture: 'CNNAutoencoderCAEBN'
  patiente_early_stopping: 20
  patiente_learning_rate: 15
  train_size: 0.8